spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.78.157:3306/bang_exam?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin123
    platform: all
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initialSize: 1
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
    database: mysql
    # 控制台sql
    show-sql: true
    open-in-view: false
    # 配置自动更新数据库结构
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: 106.14.78.157
    port: 6379
    timeout: 3000
  devtools:
    restart:
      # 需要实时更新的目录
      additional-paths: resources/**,static/**,templates/**
mybatis:
  type-aliases-package: com.bangexam.bangexam.model
  mapper-locations: classpath:/mybatis-mapper/*
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8888
logging:
  path: D:/logs

